[default]
PROJECT_NAME = "FideLLiTTy"

SECRET_KEY = "123456"

# ALLOWED_HOSTS='"127.0.0.1", "localhost"'
ALLOWED_HOSTS='"127.0.0.1", "localhost", "*"'

MONGO_HOST="localhost"
MONGO_PORT=27017
MONGO_USER="admin"
MONGO_PASSWORD="123mudar"
MONGO_DB="api-db"
MONGODB_URL = ""

MAX_CONNECTIONS_COUNT = 9
MIN_CONNECTIONS_COUNT = 9

# [development]
# DATABASE_URL = "sqlite:///:memory:"